name: glate
version: '4.0'
summary: Google translator for Linux desktop
description: |
  Glate is a desktop translator with text-to-speech support, line-by-line
  translation, and sharing/export tools.

grade: stable
confinement: strict
icon: snap/gui/icon.png
base: core24
compression: lzo

plugs:
  ffmpeg-2404:
    interface: content
    target: $SNAP/ffmpeg-platform
    default-provider: ffmpeg-2404

platforms:
  amd64:
  arm64:

apps:
  glate:
    command: usr/bin/glate
    desktop: usr/share/applications/com.ktechpit.glate.desktop
    common-id: com.ktechpit.glate
    extensions:
      - kde-neon-6
    environment:
      IS_SNAP: '1'
      PATH: "$SNAP/ffmpeg-platform/usr/bin:$PATH"
      LD_LIBRARY_PATH: "$SNAP/ffmpeg-platform/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:$LD_LIBRARY_PATH"
      QT_MEDIA_BACKEND: ffmpeg
    plugs:
      - home
      - network
      - opengl
      - x11
      - wayland
      - audio-playback
      - alsa
      - desktop
      - desktop-legacy

parts:
  glate:
    source: .
    plugin: cmake
    build-packages:
      - libx11-dev
      - libxcb1-dev
      - libx11-xcb-dev
      - pkg-config
      - libpulse-dev
    stage-packages:
      - libx11-6
      - libxcb1
      - libpulse0
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX=/usr
    override-build: |
      craftctl default

      mkdir -p ${CRAFT_PART_INSTALL}/meta/gui
      cp ${CRAFT_PART_INSTALL}/usr/share/icons/hicolor/512x512/apps/com.ktechpit.glate.png \
         ${CRAFT_PART_INSTALL}/meta/gui/icon.png

      sed -i \
        "s|^Icon=.*|Icon=${SNAP}/meta/gui/icon.png|" \
        ${CRAFT_PART_INSTALL}/usr/share/applications/com.ktechpit.glate.desktop

    prime:
      - -usr/include
      - -usr/lib/*/cmake
      - -usr/share/man
      - -usr/share/lintian
